services:
  app:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=IPS_project;User Id=sa;Password=AdminPassword@2026;TrustServerCertificate=True;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AdminPassword@2026
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
