apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: ips-app
type: Opaque
stringData:
  # ⚠️ بعد ما تعمل RDS instance، غيّر القيمة دي بالكامل بمعلومات الـ RDS بتاعتك:
  #    Server   = الـ RDS Endpoint (من صفحة الـ RDS instance في AWS Console)
  #    User Id  = الـ Master username اللي اخترته وقت إنشاء الـ RDS
  #    Password = الـ Master password اللي اخترته
  connection-string: "Server=defendx-db.c4p8o0cwm4zn.us-east-1.rds.amazonaws.com,1433;Database=IPS_project;User Id=admin;Password=mohammedhamdy;TrustServerCertificate=True;"
