apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: ips-app
type: Opaque
stringData:
  sa-password: "YourStrongPassword123!"
  connection-string: "Server=mssql-service;Database=IPS_project;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;"
