apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  namespace: ips-app
type: Opaque
stringData:

  connection-string: "Server=defendx-db.c4p8o0cwm4zn.us-east-1.rds.amazonaws.com,1433;Database=IPS_project;User Id=admin;Password=mohammedhamdy;TrustServerCertificate=True;"
