apiVersion: apps/v1
kind: Deployment
metadata:
  name: ips-app
  namespace: ips-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ips-app
  template:
    metadata:
      labels:
        app: ips-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: ips-app
          image: mohammed102003/ips-app # ← غيّر الاسم ده
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: connection-string
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: AiSettings__Endpoint
              value: "http://ai-model-service:8000/predict"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
            failureThreshold: 30   # بيدّي مهلة لحد 150 ثانية لأول migration على RDS
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ips-app-service
  namespace: ips-app
spec:
  selector:
    app: ips-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30500          # هتوصله من برا على  <VM_IP>:30500
                               # تقدر تغيره لأي رقم بين 30000-32767
