apiVersion: apps/v1
kind: Deployment
metadata:
  name: waf
  namespace: ips-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waf
  template:
    metadata:
      labels:
        app: waf
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
        - name: waf
          image: mohammed102003/ips-waf:latest
          ports:
            - containerPort: 443
          env:
            - name: BACKEND
              value: "http://ips-app-service:8080"
            - name: MODSEC_RULE_ENGINE
              value: "DetectionOnly"
            - name: NGINX_ALWAYS_TLS_REDIRECT
              value: "off"
            - name: PORT
              value: "443"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 443
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 443
            periodSeconds: 20
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: ssl-certs
              mountPath: /etc/nginx/ssl
              readOnly: true
      volumes:
        - name: nginx-config
          configMap:
            name: waf-nginx-conf
        - name: ssl-certs
          secret:
            secretName: waf-ssl-certs
---
apiVersion: v1
kind: Service
metadata:
  name: waf-service
  namespace: ips-app
spec:
  selector:
    app: waf
  type: NodePort
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30500